2025/04/22 14:55:10 [error] 30#30: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.28.0.1, server: localhost, request: "GET /api/users?page=1 HTTP/1.1", upstream: "fastcgi://172.28.0.2:9000", host: "localhost", referrer: "http://localhost/api"
2025/04/22 14:55:18 [error] 30#30: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.28.0.1, server: localhost, request: "GET /api/users?page=1 HTTP/1.1", upstream: "fastcgi://172.28.0.2:9000", host: "localhost", referrer: "http://localhost/api"
2025/04/22 14:55:26 [error] 30#30: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.28.0.1, server: localhost, request: "GET /api HTTP/1.1", upstream: "fastcgi://172.28.0.2:9000", host: "localhost"
